# Generated by Django 5.2.15 on 2026-07-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_mockemail_emailotp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MockEmail",
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="user",
        ),
        migrations.AddField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
    ]
