/**
 * ================================================================================
 * RECOMMENDED FOR YOU PAGE
 * ================================================================================
 * File: frontend/src/pages/RecommendedPage.jsx
 * 
 * Description:
 * Dedicated recommendations page accessible from the Navbar.
 * Displays AI-powered event recommendations generated using Scikit-Learn
 * Content-Based Filtering for logged in users and trending events for guests.
 */

import React from 'react';
import AIEventRecommendations from '../components/AIEventRecommendations';
import { Sparkles, Compass } from 'lucide-react';

const RecommendedPage = () => {
  return (
    <div className="w-full max-w-none px-4 sm:px-6 lg:px-12 py-10 bg-dark-bg min-h-screen">
      {/* Hero Header */}
      <div className="w-full mb-4 relative text-left">
        <div className="absolute top-1/2 left-0 w-96 h-48 bg-gradient-to-tr from-blue-500/10 to-indigo-500/10 blur-[80px] -z-10 rounded-full" />
        
        <div className="inline-flex items-center space-x-2 bg-blue-500/10 border border-blue-500/20 text-blue-400 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider mb-3">
          <Sparkles className="w-3.5 h-3.5" />
          <span>AI Recommendations Engine</span>
        </div>

        <h1 className="text-4xl sm:text-5xl font-black font-display text-dark-text mb-2">
          Recommended <span className="text-gradient-emerald">For You</span>
        </h1>
        <p className="text-sm sm:text-base text-dark-muted max-w-2xl">
          Personalized event picks generated by Scikit-Learn machine learning content analysis, matching your ticket bookings, wishlist, categories, and location preferences.
        </p>
      </div>

      {/* AI Event Recommendations Component */}
      <AIEventRecommendations 
        title="AI Personal Match Showcase" 
        subtitle="Custom curated events calculated using Content-Based TF-IDF & Cosine Similarity" 
      />
    </div>
  );
};

export default RecommendedPage;
