# Generated by Django 5.2.15 on 2026-07-04 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0004_venuebooking_payment_id_venuebooking_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cuisine_type', models.CharField(max_length=255)),
                ('price_per_plate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_guests', models.IntegerField(default=10)),
                ('max_guests', models.IntegerField(default=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catering/')),
                ('pdf_menu', models.FileField(blank=True, null=True, upload_to='catering_menus/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'plot_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='catering_services', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catering_services', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='CateringReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_reviews', to=settings.AUTH_USER_MODEL)),
                ('catering_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catering.cateringservice')),
            ],
        ),
        migrations.CreateModel(
            name='CateringPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_plate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catering_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catering.cateringservice')),
            ],
        ),
        migrations.CreateModel(
            name='CateringBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('guests_count', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_bookings', to=settings.AUTH_USER_MODEL)),
                ('venue_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catering_bookings', to='venues.venuebooking')),
                ('catering_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='catering.cateringpackage')),
                ('catering_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='catering.cateringservice')),
            ],
        ),
    ]
