# Generated by Django 5.2.15 on 2026-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_coupon_booking_payment_status_booking_qr_code_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
