# Generated by Django 5.2.15 on 2026-07-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
