# Generated by Django 5.2.15 on 2026-07-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_booking_is_checked_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket_category",
            field=models.CharField(default="Silver", max_length=50),
        ),
    ]
