# Generated by Django 5.2.15 on 2026-07-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_contactquery"),
        ("venues", "0002_venue_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="venues.venue",
            ),
        ),
    ]
