# Generated by Django 5.2.15 on 2026-07-03 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_venue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactquery",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactquery",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
