# Generated by Django 5.2.15 on 2026-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
