# Generated by Django 5.2.15 on 2026-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_alter_venuebooking_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuebooking",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="payment_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
