# Generated by Django 5.2.15 on 2026-07-04 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0004_venuebooking_payment_id_venuebooking_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="venuebooking",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="venue",
            name="catering_cuisine",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="venue",
            name="catering_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="venue",
            name="catering_min_plates",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="venue",
            name="catering_price_per_plate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="decor_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="decor_themes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="venue",
            name="dj_equipment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="venue",
            name="dj_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="has_catering",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venue",
            name="has_decor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venue",
            name="has_dj",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="catering_plates",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="use_catering",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="use_decor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="use_dj",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="venue",
            name="price_per_day",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
