# Generated by Django 5.2.15 on 2026-07-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0005_alter_venue_options_alter_venuebooking_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuebooking",
            name="catering_cuisine",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="catering_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="decor_theme",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="dj_equipment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="dj_package",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
