# Generated by Django 5.2.15 on 2026-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0006_venuebooking_catering_cuisine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="decor_themes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="venue",
            name="dj_equipment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
