# Generated by Django 5.2.15 on 2026-07-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0008_venuereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuebooking",
            name="cancel_requested",
            field=models.BooleanField(default=False),
        ),
    ]
