# Generated by Django 5.2.15 on 2026-07-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0009_venuebooking_cancel_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="category",
            field=models.CharField(
                blank=True, default="Party Plot / Lawn", max_length=100
            ),
        ),
    ]
